FROM node:latest
# RUN mkdir -p /api/config /api/src
WORKDIR /api

COPY package.json /api/package.json
COPY package-lock.json /api/package-lock.json

RUN npm install
# RUN npm run build # do this in prod

CMD ["npm", "run", "dev"]
